#!/bin/bash
#
# Monitor the state of a **local** Ceph monitor
#
# Author: Sébastien Han <sebastien.han@enovance.com>
# Based on the original script from Olaf van Zandwijk and Raghavendra Prabhu to monitor Percona XtraDB Cluster nodes.

if [[ $1 == '-h' || $1 == '--help' ]];then
    echo "Usage: $0"
    exit
fi

# if the disabled file is present, return 503. This allows
# admins to manually remove a node from a cluster easily.
if [ -e "/var/tmp/cephmoncheck.disabled" ]; then
    # Shell return-code is 1
    echo -en "HTTP/1.1 503 Service Unavailable\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n"
    echo -en "Content-Length: 51\r\n"
    echo -en "\r\n"
    echo -en "Ceph Monitor out of the quorum.\r\n"
    sleep 0.1
    exit 1
fi

CEPH=$(command -v ceph)
MONITOR=$(find -L /var/lib/ceph/mon -mindepth 1 -maxdepth 1 -type d -printf '%f\n')
MON_STATE=$($CEPH daemon mon.${MONITOR#*-} mon_status | grep state | cut -f 4 -d '"')

if [[ "${MON_STATE}" == "leader" ]] || [[ "${MON_STATE}" == "peon" ]]
then
    # Ceph Monitor state is 'Leader' or 'Peon' => return HTTP 200
    # Shell return-code is 0
    echo -en "HTTP/1.1 200 OK\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n"
    echo -en "Content-Length: 40\r\n"
    echo -en "\r\n"
    echo -en "Ceph Monitor ${MONITOR#*-} state is ${MON_STATE}.\r\n"
    sleep 0.1
    exit 0
else
    # Ceph Monitor state is not 'Leader' nor 'Peon' => return HTTP 503
    # Shell return-code is 1
    echo -en "HTTP/1.1 503 Service Unavailable\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n"
    echo -en "Content-Length: 44\r\n"
    echo -en "\r\n"
    echo -en "Ceph Monitor ${MONITOR#*-} state is ${MON_STATE}.\r\n"
    sleep 0.1
    exit 1
fi
